### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by Rayman**
Hello,

I've fixed four small issues while tring to compile this package with clang

1. Properly initialize the parent object of `message_counter`
2. `-pedantic` doesn't work on clang
3. Add proper include for `spin_some`
4. Remove unused variable

### CODE REVIEW

**Comment by Rayman** [comment]
Hello, can I get some feedback on my PR?

**Comment by daniel4ohw** [comment]
Hello @Rayman  
sorry for not replying sooner.
First of all, thank you for your contribution!
We are working on other issues in parallel and we have not had a chance to analyze it yet.
I hope you will appreciate this.
I'll get back to you as soon as possible.

**Comment by TimStricker** [comment]
Just FYI: I've had the same issue with the message counter (`-Wmissing-braces`) on the `noetic-devel` branch. Also in the `off_highway_radar` and `off_highway_general_purpose_radar`. 

`-Wpedantic` worked for me though, using clang 15.0.7.

**Comment by Rayman** [comment]
I compiled with clang 15. If I turn on `-pedantic` I get errors from PCL, which I can't fix here

**Comment by Rayman** [comment]
@daniel4ohw did you have time to take a look at this PR? It's only a few minor changes and should be reviewable in a minute

**Comment by daniel4ohw** [comment]
@Rayman Thank you for your request.
We are currently working on other topics that will also appear in the repo soon. We have planned this PR for next week.

**Comment by Rayman** [comment]
Thank you for the reply!

**Comment by rcp1-beg** [comment]
@Rayman Can you sign your commits with a GPG / SSH key? Although not stated anywhere yet, I would like to enforce it in this repo. Thanks!

**Comment by Rayman** [comment]
Done! I've never signed my commits before, so hopefully this works

**Comment by daniel4ohw** [comment]
Hi @Rayman 
unfortunately we will not be able to finish the contribution of the commit this week due to illness. 
But good news - we have made further adjustments to make it compatible with Clang (at least for now). The update will be available soon..
We still have some content-related issues ahead of us, so we are not focusing on supporting Clang for the next few months. If you have any problems just let us know.

**Comment by rcp1-beg** [comment]
Hi @Rayman,

we've just pushed our fixes for Clang. I took some of your commits over but did not remove the pedantic warnings in general and rather removed only the problematic warnings for GNU extensions and anonymous structs. Please check if 0.5.1 works for you with Clang. 

If 0.5.1 works for you, I'll close this PR.

Also, I've dropped the commit GPG signing for the moment due to limitations of [GitHub](https://github.com/orgs/community/discussions/10410). Sorry about your wasted effort!

**Comment by Rayman** [comment]
[0.5.1](https://github.com/bosch-engineering/off_highway_sensor_drivers/commit/fd18f651b06222e93a2bba7ef6e20965c8185219) seems to compile on my PC with clang. Thank you! I'll close this PR then.

**Comment by TimStricker** [comment]
@rcp1-beg Are you going to merge these fixes for `noetic-devel` as well? If not planned, I could set up a PR because I already did it on my fork anyway.

**Comment by daniel4ohw** [comment]
Hello @TimStricker 
we want to kept the noetic branch inactive due to numerous updates on the humble branch. 
However, if you'd like, you're welcome to publish your private fork.
Thanks for your efforts!
Daniel

**Pull request closed without merging**
